# Global settings
global:
  image:
    tag: v.1.1
    pullPolicy: IfNotPresent

# Frontend Configuration
frontend:
  enabled: true
  replicaCount: 1
  image:
    repository: quay.io/s0926760809/fintech-ebpf-frontend
    tag: "v3.0-fullfeatured"
  service:
    port: 80
    targetPort: 80

# Backend Services Common Configuration
backend:
  replicaCount: 1

backendServices:
  - name: trading-api
    image:
      repository: quay.io/s0926760809/fintech-trading-api
      tag: v1.2
    service:
      port: 8080
      targetPort: 30080
    env:
      - name: SERVER_PORT
        value: "30080"
      - name: DATABASE_HOST
        value: "my-fintech-app-postgresql"
      - name: DATABASE_USER
        value: "fintech_user"
      - name: DATABASE_PASSWORD
        value: "password123"
      - name: DATABASE_NAME
        value: "fintech_demo"
      - name: REDIS_HOST
        value: "my-fintech-app-redis-master"
      - name: REDIS_PASSWORD
        value: ""
  - name: risk-engine
    image:
      repository: quay.io/fintech/ebpf-risk-engine
    service:
      port: 8081
      targetPort: 8081
    env:
      - name: DATABASE_HOST
        value: "my-fintech-app-postgresql"
      - name: DATABASE_USER
        value: "fintech_user"
      - name: DATABASE_PASSWORD
        value: "password123"
      - name: DATABASE_NAME
        value: "fintech_demo"
      - name: REDIS_HOST
        value: "my-fintech-app-redis-master"
      - name: REDIS_PASSWORD
        value: ""
  - name: payment-gateway
    image:
      repository: quay.io/fintech/ebpf-payment-gateway
    service:
      port: 8082
      targetPort: 8082
    env:
      - name: DATABASE_HOST
        value: "my-fintech-app-postgresql"
      - name: DATABASE_USER
        value: "fintech_user"
      - name: DATABASE_PASSWORD
        value: "password123"
      - name: DATABASE_NAME
        value: "fintech_demo"
      - name: REDIS_HOST
        value: "my-fintech-app-redis-master"
      - name: REDIS_PASSWORD
        value: ""
  - name: audit-service
    image:
      repository: quay.io/fintech/ebpf-audit-service
    service:
      port: 8083
      targetPort: 8083
    env:
      - name: DATABASE_HOST
        value: "my-fintech-app-postgresql"
      - name: DATABASE_USER
        value: "fintech_user"
      - name: DATABASE_PASSWORD
        value: "password123"
      - name: DATABASE_NAME
        value: "fintech_demo"
      - name: REDIS_HOST
        value: "my-fintech-app-redis-master"
      - name: REDIS_PASSWORD
        value: ""

# Database (PostgreSQL) Dependency Configuration
postgresql:
  enabled: true
  auth:
    username: "fintech_user"
    password: "password123"
    database: "fintech_demo"
  primary:
    persistence:
      enabled: true
      size: 10Gi

# Cache (Redis) Dependency Configuration
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 5Gi

# Ingress Configuration
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: fintech.local
      paths:
        - path: /
          pathType: Prefix
  tls: [] 