{{- if .Values.networkPolicy.enabled }}
# Network Policy for Frontend
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "fintech-chart.fullname" . }}-frontend-netpol
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fintech-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  podSelector:
    matchLabels:
      {{- include "fintech-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "fintech-chart.selectorLabels" . | nindent 10 }}
          app.kubernetes.io/component: backend
    - podSelector: {}  # Allow from any pod in the same namespace
    ports:
    - protocol: TCP
      port: 80
  egress:
  - to: []  # Allow all egress
---
# Network Policy for Backend Services
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "fintech-chart.fullname" . }}-backend-netpol
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fintech-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  podSelector:
    matchLabels:
      {{- include "fintech-chart.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "fintech-chart.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: 8080  # Trading API
    - protocol: TCP
      port: 8081  # Risk Engine
    - protocol: TCP
      port: 8082  # Payment Gateway
    - protocol: TCP
      port: 8083  # Audit Service
  egress:
  - to: []  # Allow all egress for database and external API connections
---
# Network Policy for Database Access
{{- if or .Values.postgresql.enabled .Values.redis.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "fintech-chart.fullname" . }}-database-netpol
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fintech-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgresql
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "fintech-chart.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: 5432  # PostgreSQL
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "fintech-chart.fullname" . }}-redis-netpol
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fintech-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: redis
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "fintech-chart.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: 6379  # Redis
{{- end }}
{{- end }} 