# Frontend Service
{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fintech-chart.fullname" . }}-frontend
  labels:
    {{- include "fintech-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fintech-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
---
{{- end }}

# Trading API Service
{{- if .Values.tradingApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fintech-chart.fullname" . }}-trading-api
  labels:
    {{- include "fintech-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: trading-api
spec:
  type: {{ .Values.tradingApi.service.type }}
  ports:
    - port: {{ .Values.tradingApi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fintech-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: trading-api
---
{{- end }}

# Risk Engine Service
{{- if .Values.riskEngine.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fintech-chart.fullname" . }}-risk-engine
  labels:
    {{- include "fintech-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: risk-engine
spec:
  type: {{ .Values.riskEngine.service.type }}
  ports:
    - port: {{ .Values.riskEngine.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fintech-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: risk-engine
---
{{- end }}

# Payment Gateway Service
{{- if .Values.paymentGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fintech-chart.fullname" . }}-payment-gateway
  labels:
    {{- include "fintech-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: payment-gateway
spec:
  type: {{ .Values.paymentGateway.service.type }}
  ports:
    - port: {{ .Values.paymentGateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fintech-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: payment-gateway
---
{{- end }}

# Audit Service
{{- if .Values.auditService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fintech-chart.fullname" . }}-audit-service
  labels:
    {{- include "fintech-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: audit-service
spec:
  type: {{ .Values.auditService.service.type }}
  ports:
    - port: {{ .Values.auditService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fintech-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: audit-service
{{- end }} 