# Frontend Service
{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fintech-chart.frontend.name" . }}
  labels:
    {{- include "fintech-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.frontend.service.type "NodePort") .Values.frontend.service.nodePort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
  selector:
    {{- include "fintech-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
---
{{- end }}

# Trading API Service
{{- if .Values.tradingApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fintech-chart.trading-api.name" . }}
  labels:
    {{- include "fintech-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: trading-api
spec:
  type: {{ .Values.tradingApi.service.type }}
  ports:
    - port: {{ .Values.tradingApi.service.port }}
      targetPort: {{ .Values.tradingApi.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "fintech-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: trading-api
---
{{- end }}

# Risk Engine Service
{{- if .Values.riskEngine.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fintech-chart.risk-engine.name" . }}
  labels:
    {{- include "fintech-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: risk-engine
spec:
  type: {{ .Values.riskEngine.service.type }}
  ports:
    - port: {{ .Values.riskEngine.service.port }}
      targetPort: {{ .Values.riskEngine.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "fintech-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: risk-engine
---
{{- end }}

# Payment Gateway Service
{{- if .Values.paymentGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fintech-chart.payment-gateway.name" . }}
  labels:
    {{- include "fintech-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: payment-gateway
spec:
  type: {{ .Values.paymentGateway.service.type }}
  ports:
    - port: {{ .Values.paymentGateway.service.port }}
      targetPort: {{ .Values.paymentGateway.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "fintech-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: payment-gateway
---
{{- end }}

# Audit Service
{{- if .Values.auditService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fintech-chart.audit-service.name" . }}
  labels:
    {{- include "fintech-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: audit-service
spec:
  type: {{ .Values.auditService.service.type }}
  ports:
    - port: {{ .Values.auditService.service.port }}
      targetPort: {{ .Values.auditService.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "fintech-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: audit-service
{{- end }} 