# Frontend Service
{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fintech-chart.frontend.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fintech-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "fintech-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
---
{{- end }}

# Trading API Service
{{- if .Values.backend.tradingApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fintech-chart.trading-api.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fintech-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: trading-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.backend.tradingApi.port }}"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.tradingApi.port }}
      targetPort: {{ .Values.backend.tradingApi.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "fintech-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: trading-api
---
{{- end }}

# Risk Engine Service
{{- if .Values.backend.riskEngine.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fintech-chart.risk-engine.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fintech-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: risk-engine
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.backend.riskEngine.port }}"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.riskEngine.port }}
      targetPort: {{ .Values.backend.riskEngine.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "fintech-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: risk-engine
---
{{- end }}

# Payment Gateway Service
{{- if .Values.backend.paymentGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fintech-chart.payment-gateway.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fintech-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: payment-gateway
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.backend.paymentGateway.port }}"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.paymentGateway.port }}
      targetPort: {{ .Values.backend.paymentGateway.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "fintech-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: payment-gateway
---
{{- end }}

# Audit Service
{{- if .Values.backend.auditService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fintech-chart.audit-service.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fintech-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: audit-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.backend.auditService.port }}"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.auditService.port }}
      targetPort: {{ .Values.backend.auditService.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "fintech-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: audit-service
{{- end }} 