apiVersion: v1
kind: Namespace
metadata:
  name: fintech-demo
  labels:
    name: fintech-demo
    security.policy: "strict"
    monitoring.enabled: "true"
    tetragon.io/policy: "enabled"
  annotations:
    description: "金融微服務演示環境 - 包含故意安全漏洞用於eBPF監控演示"
    version: "2.0.0"
    contact: "fintech-security-team"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: fintech-demo-quota
  namespace: fintech-demo
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: fintech-demo-limits
  namespace: fintech-demo
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - max:
      cpu: "2"
      memory: "4Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
    type: Container 