server:
  port: "30080"
  host: "0.0.0.0"
  mode: "release"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "password"
  dbname: "fintech_demo"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

trading:
  max_order_value: 100000.0
  supported_symbols: ["AAPL", "GOOGL", "MSFT", "TSLA", "AMZN"]
  market_open_hour: 9
  market_close_hour: 16 