# fintech-chart 的預設值
# 這是一個 YAML 格式的檔案。
# 在這裡聲明可以在模板中使用的變數。

# 全域設定
replicaCount: 1

image:
  pullPolicy: IfNotPresent
  # 全域映像檔標籤，可被各個服務獨立覆寫
  tag: "v1.0"

imagePullSecrets:
  - name: quay-pull-secret
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

# -- 前端服務設定 --
frontend:
  enabled: true
  replicaCount: 1
  image:
    repository: quay.io/s0926760809/fintech-demo/frontend
    tag: "v1.2"
    pullPolicy: Always
  service:
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30088
  env:
    VITE_BACKEND_URLS: "trading:http://{{ include \"fintech-chart.trading-api.name\" . }}:{{ .Values.tradingApi.service.port }},risk:http://{{ include \"fintech-chart.risk-engine.name\" . }}:{{ .Values.riskEngine.service.port }},payment:http://{{ include \"fintech-chart.payment-gateway.name\" . }}:{{ .Values.paymentGateway.service.port }},audit:http://{{ include \"fintech-chart.audit-service.name\" . }}:{{ .Values.auditService.service.port }}"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# --- 後端微服務設定 ---

tradingApi:
  enabled: true
  replicaCount: 1
  image:
    repository: quay.io/s0926760809/fintech-demo/trading-api
    tag: "v1.0"
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

riskEngine:
  enabled: true
  replicaCount: 1
  image:
    repository: quay.io/s0926760809/fintech-demo/risk-engine
    tag: "v1.0"
  service:
    type: ClusterIP
    port: 8081
    targetPort: 8081
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

paymentGateway:
  enabled: true
  replicaCount: 1
  image:
    repository: quay.io/s0926760809/fintech-demo/payment-gateway
    tag: "v1.0"
  service:
    type: ClusterIP
    port: 8082
    targetPort: 8082
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

auditService:
  enabled: true
  replicaCount: 1
  image:
    repository: quay.io/s0926760809/fintech-demo/audit-service
    tag: "v1.0"
  service:
    type: ClusterIP
    port: 8083
    targetPort: 8083
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# --- 資料庫與其他依賴設定 ---
# 在生產環境中，建議使用外部管理的資料庫。
# 這裡預設為不透過此 Chart 部署，但保留了選項。

postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    postgresPassword: "fintech123"
    username: "fintech"
    password: "password"
    database: "fintech_db"
  primary:
    persistence:
      enabled: true
      size: 8Gi

redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 8Gi

# Ingress 配置 - 可选择启用以暴露服务
ingress:
  enabled: true
  host: "fintech-demo.local"
  className: "nginx"
  annotations: {}
  tls: []

# 环境变量配置
env:
  DATABASE_URL: "postgresql://fintech:password@postgresql:5432/fintech_db"
  REDIS_URL: "redis://redis:6379"
  LOG_LEVEL: "info" 