# 金融微服務 eBPF 演示系統 - 開發環境配置

# 全局配置
global:
  imageRegistry: "quay.io/s0926760809/fintech-demo"
  imageTag: "latest"
  imagePullPolicy: "Always"
  storageClass: "standard"

# 通用配置
nameOverride: ""
fullnameOverride: ""

commonLabels: {}
commonAnnotations: {}

# 鏡像拉取祕密（開發環境可以設為空）
imagePullSecrets: []

# Service Account 配置
serviceAccount:
  create: true
  name: ""
  annotations: {}

# 映像配置
image:
  registry: "quay.io/s0926760809/fintech-demo"
  tag: "latest"
  pullPolicy: "Always"

# 前端配置
frontend:
  enabled: true
  replicaCount: 1
  
  config:
    apiUrl: "http://localhost:8080"
    wsUrl: "ws://localhost:8080"
  
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
  
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 5
  
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
  
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 101
    fsGroup: 101
  
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
  
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}

# 後端服務配置
backend:
  tradingApi:
    enabled: true
    replicaCount: 1
    port: 8080
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
  
  riskEngine:
    enabled: true
    replicaCount: 1
    port: 8081
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
  
  paymentGateway:
    enabled: true
    replicaCount: 1
    port: 8082
    resources:
      limits:
        cpu: 300m
        memory: 256Mi
      requests:
        cpu: 150m
        memory: 128Mi
  
  auditService:
    enabled: true
    replicaCount: 1
    port: 8083
    resources:
      limits:
        cpu: 300m
        memory: 256Mi
      requests:
        cpu: 150m
        memory: 128Mi

# 數據庫配置
postgresql:
  enabled: true
  auth:
    username: "fintech_user"
    password: "fintech_password_dev"
    database: "fintech_db"
  primary:
    service:
      ports:
        postgresql: 5432
    persistence:
      enabled: true
      size: 8Gi
  external:
    host: ""
    port: 5432
    database: "fintech_db"
    username: "fintech_user"

# Redis 配置
redis:
  enabled: true
  auth:
    enabled: false
  master:
    service:
      ports:
        redis: 6379
    persistence:
      enabled: true
      size: 4Gi
  external:
    host: ""
    port: 6379

# 網路策略
networkPolicy:
  enabled: true
  ingress:
    enabled: true
  egress:
    enabled: true

# Ingress 配置
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: fintech-demo.local
      paths:
        - path: /
          pathType: Prefix
          service: frontend
        - path: /api/trading
          pathType: Prefix
          service: trading-api
        - path: /api/risk
          pathType: Prefix
          service: risk-engine
        - path: /api/payment
          pathType: Prefix
          service: payment-gateway
        - path: /api/audit
          pathType: Prefix
          service: audit-service
  tls: []

# 水平自動擴展
autoscaling:
  enabled: false 