apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: fintech-demo
data:
  redis.conf: |
    # Redis配置 - 故意使用不安全的設置用於演示
    bind 0.0.0.0
    port 6379
    
    # 故意使用弱密碼
    requirepass redis_password
    
    # 啟用持久化
    save 900 1
    save 300 10
    save 60 10000
    
    # 日誌級別
    loglevel notice
    
    # 最大內存設置
    maxmemory 512mb
    maxmemory-policy allkeys-lru
    
    # 故意啟用危險命令
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    rename-command EVAL ""
    
    # 允許危險的配置修改
    enable-protected-configs yes
    enable-debug-command yes
    
    # 故意暴露更多信息
    server-cpulist 0-3
    io-threads 4
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: fintech-demo
type: Opaque
data:
  # redis-password: "redis_password" (base64編碼)
  redis-password: cmVkaXNfcGFzc3dvcmQ=
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: fintech-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: fintech-demo
  labels:
    app: redis
    tier: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        tier: cache
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
        tetragon.io/monitor: "cache"
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        command:
        - redis-server
        - /etc/redis/redis.conf
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-password
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis
        - name: redis-storage
          mountPath: /data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        # 故意使用不安全的安全上下文
        securityContext:
          allowPrivilegeEscalation: true
          runAsUser: 0  # 以root身份運行
          capabilities:
            add:
            - NET_ADMIN  # 故意添加不必要的權限
        livenessProbe:
          exec:
            command:
            - redis-cli
            - --no-auth-warning
            - -a
            - $(REDIS_PASSWORD)
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - --no-auth-warning
            - -a
            - $(REDIS_PASSWORD)
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
      # Redis Exporter for Prometheus (可選)
      - name: redis-exporter
        image: oliver006/redis_exporter:latest
        ports:
        - containerPort: 9121
          name: metrics
        env:
        - name: REDIS_ADDR
          value: "redis://localhost:6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-password
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: fintech-demo
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  - port: 9121
    targetPort: 9121
    protocol: TCP
    name: metrics
  selector:
    app: redis 