# Kustomize 基礎配置
# 這個檔案定義了所有環境共享的基礎資源。

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 包含的資源列表
resources:
  - namespace.yaml
  - database/postgresql.yaml
  - database/redis.yaml
  - frontend/frontend-deployment.yaml
  - microservices/risk-engine.yaml
  - microservices/trading-api.yaml
  # 提示: 如果有新的 microservice yaml, 需要加到這裡 