server:
  port: "30082"
  host: "0.0.0.0"
  mode: "release"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "password"
  dbname: "fintech_demo"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

payment:
  provider_api_key: "pk_test_51234567890abcdef"
  provider_secret: "sk_test_secret_key_demo_123"
  external_endpoints:
    payment_processor: "https://api.stripe.com"
    bank_gateway: "https://bank-api.demo.com"
    fraud_checker: "https://fraud-api.demo.com"
  dns_servers: ["8.8.8.8", "8.8.4.4", "1.1.1.1"] 